import Sidebar from "@/components/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className=" h-screen w-screen flex">
        <Sidebar />
        <div className=" w-full h-screen relative">
            <header className=" shadow-sm absolute bg-white z-40 border-b w-full h-12 ">
                
            </header>
                {children}
        </div>
    </div>
  );
}
